export const indiaData = {
    "State": ["City"],
    "AndhraPradesh": [
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Nellore",
      "Kurnool",
      "Rajahmundry",
      "Tirupati",
      "Kakinada",
      "Kadapa",
      "Anantapur"
    ],
    "ArunachalPradesh": [
      "Itanagar",
      "Naharlagun",
      "Pasighat",
      "Daporijo",
      "Ziro",
      "Aalo",
      "Bomdila",
      "Along",
      "Tezu"
    ],
    "Assam": [
      "Guwahati",
      "Dibrugarh",
      "Jorhat",
      "Silchar",
      "Tezpur",
      "Nagaon",
      "Tinsukia",
      "Bongaigaon",
      "Dhubri",
      "Goalpara"
    ],
    "Bihar": [
      "Patna",
      "Gaya",
      "Bhagalpur",
      "Muzaffarpur",
      "Purnia",
      "Darbhanga",
      "Arrah",
      "Begusarai",
      "Katihar",
      "Chhapra"
    ],
    "Chhattisgarh": [
      "Raipur",
      "Bhilai",
      "Durg",
      "Bilaspur",
      "Korba",
      "Raigarh",
      "Ambikapur",
      "Rajnandgaon",
      "Jagdalpur",
      "Kanker"
    ],
    "Goa": [
      "Panaji",
      "Margao",
      "Vasco da Gama",
      "Ponda",
      "Mapusa",
      "Bicholim",
      "Curchorem",
      "Sanguem",
      "Valpoi",
      "Cuncolim"
    ],
    "Gujarat": [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Bhavnagar",
      "Jamnagar",
      "Junagadh",
      "Gandhinagar",
      "Nadiad",
      "Anand"
    ],
    "Haryana": [
      "Faridabad",
      "Gurugram",
      "Panipat",
      "Ambala",
      "Yamunanagar",
      "Rohtak",
      "Hisar",
      "Karnal",
      "Sonipat",
      "Panchkula"
    ],
    "HimachalPradesh": [
      "Shimla",
      "Mandi",
      "Solan",
      "Dharamshala",
      "Bilaspur",
      "Kullu",
      "Nahan",
      "Chamba",
      "Hamirpur",
      "Una"
    ],
    "Jharkhand": [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Bokaro",
      "Hazaribagh",
      "Deoghar",
      "Giridih",
      "Ramgarh",
      "Chatra",
      "Gumla"
    ],
    "Karnataka": [
      "Bengaluru",
      "Mysuru",
      "Hubballi",
      "Mangaluru",
      "Belagavi",
      "Dharwad",
      "Bidar",
      "Gulbarga",
      "Ballari",
      "Hosapete"
    ],
    "Kerala": [
      "Thiruvananthapuram",
      "Kochi",
      "Kozhikode",
      "Kollam",
      "Thrissur",
      "Kottayam",
      "Palakkad",
      "Alappuzha",
      "Kannur",
      "Thalassery"
    ],
    "Madhya Pradesh": [
      "Bhopal",
      "Indore",
      "Jabalpur",
      "Gwalior",
      "Ujjain",
      "Sagar",
      "Dewas",
      "Satna",
      "Ratlam",
      "Rewa"
    ],
    "Maharashtra": [
      "Mumbai",
      "Pune",
      "Nagpur",
      "Thane",
      "Nashik",
      "Aurangabad",
      "Solapur",
      "Amravati",
      "Nanded",
      "Kolhapur"
    ],
    "Manipur": [
      "Imphal",
      "Bishnupur",
      "Churachandpur",
      "Thoubal",
      "Kakching",
      "Ukhrul",
      "Senapati",
      "Tamenglong",
      "Jiribam",
      "Kangpokpi"
    ],
    "Meghalaya": [
      "Shillong",
      "Tura",
      "Jowai",
      "Nongpoh",
      "Williamnagar",
      "Baghmara",
      "Resubelpara",
      "Khliehriat",
      "Mairang",
      "Mawkyrwat"
    ],
    "Mizoram": [
      "Aizawl",
      "Lunglei",
      "Saiha",
      "Champhai",
      "Serchhip",
      "Kolasib",
      "Lawngtlai",
      "Hnahthial",
      "Khawzawl",
      "Saitual"
    ],
    "Nagaland": [
      "Kohima",
      "Dimapur",
      "Mokokchung",
      "Tuensang",
      "Wokha",
      "Zunheboto",
      "Phek",
      "Mon",
      "Longleng",
      "Kiphire"
    ],
    "Odisha": [
      "Bhubaneswar",
      "Cuttack",
      "Rourkela",
      "Berhampur",
      "Sambalpur",
      "Puri",
      "Balasore",
      "Bhadrak",
      "Baripada",
      "Jharsuguda"
    ],
    "Punjab": [
      "Ludhiana",
      "Amritsar",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "Hoshiarpur",
      "Mohali",
      "Batala",
      "Moga",
      "Pathankot"
    ],
    "Rajasthan": [
      "Jaipur",
      "Jodhpur",
      "Kota",
      "Bikaner",
      "Ajmer",
      "Udaipur",
      "Bhilwara",
      "Alwar",
      "Sikar",
      "Pali"
    ],
    "Sikkim": [
      "Gangtok",
      "Namchi"
    ]
}
